from utils.exception import CustomAPIException